resource_types:
- name: kubernetes
  type: docker-image
  source:
    repository: zlabjp/kubernetes-resource
    tag: "1.12"
resources:
- name: app
  type: git
  source:
    uri: https://github.com/jacopen/simple-php.git
- name: container-image
  type: docker-image
  source:
    username: ((registry_user))
    repository: jacopen/simple-php
    password: ((registry_password))
- name: kubernetes
  type: kubernetes
  source:
    kubeconfig: ((kubeconfig))
jobs:
- name: unit-test
  plan:
  - get: app
    trigger: true
  - task: run-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: alpine
      run:
        path: sh
        args:
        - -c
        - |
          echo "///WRITE YOUR TEST CODE///"
      inputs:
      - name: app
- name: build-image
  plan:
  - get: app
    passed:
    - unit-test
    trigger: true
  - put: container-image
    params:
      build: app
      tag_as_latest: true
      tag_file: app/.git/refs/heads/master
      tag_prefix: stg-
- name: kubernetes-deploy-production
  plan:
  - get: app
    passed:
    - build-image
    trigger: true
  - task: rewrite-manifest
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: containerdaysjp/alpine-git-sed
      run:
        path: sh
        args:
        - -c
        - |
          cp -R app/* app-output/
          cd app-output/manifests/
          ls
          sed -i '' -e "s/TAG/stg-`cat ../../app/.git/refs/heads/master`/" deployment.yaml
          cat deployment.yaml
      inputs:
      - name: app
      outputs:
      - name: app-output
  - put: kubernetes
    params:
      kubectl: apply -f app-output/manifests/
      wait_until_ready_selector: app=simple-php
