apiVersion: v1
kind: Service
metadata:
  name: simple-php
  labels:
    app: simple-php
spec:
  # type: NodePort 
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80
  selector:
    app: simple-php
